<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Postal de la semana — TurismoSV</title><link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">@vite(['resources/css/app.css','resources/js/app.js'])<x-social-meta title="Postal de la semana — TurismoSV" description="Descubre El Salvador a través de las fotografías de nuestra comunidad viajera." />
<x-analytics />
</head><body class="postcard-page">
<header class="place-header"><a href="{{ route('home') }}"><img src="{{ asset('brand/logo-turismosv.svg') }}" alt="TurismoSV"></a><nav><a href="{{ route('explore') }}">Explorar</a><a href="{{ route('rankings.index') }}">Rankings</a>@auth<a href="{{ route('profile') }}">Mi perfil</a>@endauth</nav></header>
<main class="postcard-shell"><section class="postcard-hero"><p class="eyebrow">Concurso comunitario</p><h1>Una mirada de El Salvador, elegida por la comunidad.</h1><p>Participan únicamente fotografías aprobadas y con autorización de exhibición. Cada cuenta verificada dispone de un voto semanal y no puede votar por su propia imagen.</p></section>
@if(session('postcard_status'))<div class="status-message">{{ session('postcard_status') }}</div>@endif @if($errors->any())<div class="status-error">{{ $errors->first() }}</div>@endif
@if($winner)<section class="postcard-winner"><img src="{{ route('photos.show',$winner->photo->public_id) }}" alt="{{ $winner->photo->alt_text ?: 'Postal ganadora de '.$winner->photo->place->name }}"><div><p class="eyebrow">Última postal ganadora</p><h2>{{ $winner->photo->place->name }}</h2><p>Fotografía de {{ $winner->photo->user->name }} · {{ $winner->votes_count }} votos registrados</p></div></section>@endif
<section class="postcard-current"><div class="section-heading"><div><p class="eyebrow">Semana del {{ \Carbon\Carbon::parse($week)->translatedFormat('d M') }}</p><h2>Postales participantes</h2></div><p>El conteo visible es informativo. La selección se cierra y registra administrativamente después de terminar la semana.</p></div><div class="postcard-grid">@forelse($entries as $entry)<article><img src="{{ route('photos.show',$entry->photo->public_id) }}" alt="{{ $entry->photo->alt_text ?: 'Fotografía de '.$entry->photo->place->name }}"><div><small>{{ $entry->photo->place->department->name }}</small><h3>{{ $entry->photo->place->name }}</h3><p>Por {{ $entry->photo->user->name }}</p><footer><strong>{{ $entry->votes_count }} {{ $entry->votes_count===1?'voto':'votos' }}</strong>@auth @if(auth()->user()->hasVerifiedEmail())<form method="post" action="{{ route('postcards.vote',$entry) }}">@csrf<button @disabled($userVote)>Votar</button></form>@endif @else<a href="{{ route('login') }}">Ingresar para votar</a>@endauth</footer></div></article>@empty<p class="postcard-empty">La convocatoria acaba de abrir. Aún no hay fotografías participantes.</p>@endforelse</div></section>
@auth @if(auth()->user()->hasVerifiedEmail())<section class="postcard-nominate"><div><p class="eyebrow">Participa</p><h2>Postula una fotografía aprobada</h2><p>Tu autoría permanece acreditada. Solo aparecen aquí tus fotografías que ya superaron moderación.</p></div><div>@forelse($eligiblePhotos as $photo)<form method="post" action="{{ route('postcards.nominate',$photo) }}">@csrf<img src="{{ route('photos.show',$photo->public_id) }}" alt=""><span>{{ $photo->place->name }}</span><button>Postular</button></form>@empty<p>No tienes fotografías aprobadas disponibles para esta semana.</p>@endforelse</div></section>@endif @endauth
@auth @if(auth()->user()->role==='admin')<form method="post" action="{{ route('admin.postcards.select') }}" class="postcard-admin">@csrf<label>Cerrar una semana anterior<input type="date" name="week_start" required></label><button class="approve-button">Seleccionar mayor votación</button></form>@endif @endauth
</main></body></html>
