<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Catálogo fundador — TurismoSV</title><link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">@vite(['resources/css/app.css','resources/js/app.js'])</head><body class="catalog-admin-page">
<header class="place-header"><a href="{{ route('home') }}"><img src="{{ asset('brand/logo-turismosv.svg') }}" alt="TurismoSV"></a><nav><a href="{{ route('admin.places.index') }}">Fichas editoriales</a><a href="{{ route('profile') }}">Mi perfil</a></nav></header>
<main class="founder-shell"><section class="founder-hero"><div><p class="eyebrow">Prelanzamiento responsable</p><h1>Catálogo fundador</h1><p>Una cola de trabajo para investigar, contactar y obtener material autorizado. Estar aquí no equivale a una recomendación ni a una verificación pública.</p></div><strong>{{ $metrics['total'] }}<small>candidatos</small></strong></section>
@if(session('founder_status'))<div class="status-message">{{ session('founder_status') }}</div>@endif
@if($errors->any())<div class="status-error">{{ $errors->first() }}</div>@endif
<section class="founder-metrics"><article><b>{{ $metrics['published'] }}</b><span>publicados</span></article><article><b>{{ $metrics['ready'] }}</b><span>listos para revisión</span></article><article><b>{{ $metrics['without_source'] }}</b><span>fuentes específicas pendientes</span></article><article><b>{{ $metrics['without_contact'] }}</b><span>contactos por gestionar</span></article><article><b>{{ $metrics['without_photos'] }}</b><span>sin fotos autorizadas</span></article></section>
<section class="founder-coverage"><div><p class="eyebrow">Cobertura territorial</p><h2>14 departamentos representados</h2></div><div>@foreach($departments as $department)<span><b>{{ $department->founder_places_count }}</b> {{ $department->name }}</span>@endforeach</div></section>
<section class="founder-list"><div class="section-heading"><div><p class="eyebrow">Flujo editorial</p><h2>Inventario de trabajo</h2></div><p>La publicación solo se habilita desde la ficha editorial, con fuente identificada y fecha de comprobación.</p></div>
@foreach($places as $place)<article class="founder-card"><div class="founder-place"><span>{{ $place->department->name }} · {{ $place->category->name }}</span><h3>{{ $place->name }}</h3><p>{{ $place->publication_status === 'published' ? 'Ficha pública existente; sus datos todavía deben auditarse.' : 'Borrador privado, no visible en el catálogo público.' }}</p><a href="{{ route('admin.places.edit',$place) }}">Abrir ficha editorial →</a></div>
<form method="post" action="{{ route('admin.founder.update',$place) }}">@csrf @method('PUT')
<label>Prioridad<select name="founder_priority"><option value="high" @selected($place->founder_priority==='high')>Alta</option><option value="medium" @selected($place->founder_priority==='medium')>Media</option><option value="low" @selected($place->founder_priority==='low')>Baja</option></select></label>
<label>Etapa<select name="founder_stage"><option value="candidate" @selected($place->founder_stage==='candidate')>Candidato</option><option value="researching" @selected($place->founder_stage==='researching')>Investigando</option><option value="contacting" @selected($place->founder_stage==='contacting')>Contactando</option><option value="ready" @selected($place->founder_stage==='ready')>Listo para revisión</option><option value="published" @selected($place->founder_stage==='published')>Publicado</option></select></label>
<label>Contacto<select name="founder_contact_status"><option value="not_started" @selected($place->founder_contact_status==='not_started')>Sin iniciar</option><option value="identified" @selected($place->founder_contact_status==='identified')>Identificado</option><option value="contacted" @selected($place->founder_contact_status==='contacted')>Contactado</option><option value="responded" @selected($place->founder_contact_status==='responded')>Respondió</option><option value="declined" @selected($place->founder_contact_status==='declined')>No participará</option></select></label>
<label>Fotografías<select name="founder_photo_status"><option value="missing" @selected($place->founder_photo_status==='missing')>Pendientes</option><option value="requested" @selected($place->founder_photo_status==='requested')>Solicitadas</option><option value="authorized" @selected($place->founder_photo_status==='authorized')>Autorizadas</option><option value="community" @selected($place->founder_photo_status==='community')>Comunitarias</option></select></label>
<label>Persona de contacto<input name="founder_contact_name" value="{{ $place->founder_contact_name }}"></label><label>Correo<input type="email" name="founder_contact_email" value="{{ $place->founder_contact_email }}"></label><label class="wide">Notas<textarea name="founder_notes" rows="2">{{ $place->founder_notes }}</textarea></label><button class="approve-button">Guardar seguimiento</button></form></article>@endforeach</section></main></body></html>
