<?php
namespace Tests\Feature;
use App\Models\Place;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\DB;use Tests\TestCase;
class SeoAnalyticsTest extends TestCase { use RefreshDatabase;
 public function test_sitemap_contains_only_canonical_public_content(): void { $this->seed();$draft=Place::where('publication_status','draft')->first();$response=$this->get(route('seo.sitemap'))->assertOk()->assertHeader('content-type','application/xml');$response->assertSee(route('home'),false)->assertSee(route('places.show',Place::where('publication_status','published')->first()),false)->assertDontSee(route('places.show',$draft),false);$this->get(route('seo.robots'))->assertOk()->assertSee('Disallow: /administracion')->assertSee(route('seo.sitemap')); }
 public function test_public_views_are_aggregated_without_visitor_identifiers(): void { $this->seed();$this->get(route('home'))->assertOk();$this->get(route('home'))->assertOk();$this->assertDatabaseHas('daily_page_metrics',['metric_date'=>today()->toDateString(),'page_key'=>'home','views'=>2]);$columns=DB::getSchemaBuilder()->getColumnListing('daily_page_metrics');$this->assertNotContains('ip_address',$columns);$this->assertNotContains('user_id',$columns); }
 public function test_admin_only_can_view_aggregate_analytics(): void { $this->seed();$user=User::factory()->create(['email_verified_at'=>now()]);$admin=User::factory()->create(['role'=>'admin','email_verified_at'=>now()]);$this->actingAs($user)->get(route('admin.analytics'))->assertForbidden();$this->actingAs($admin)->get(route('admin.analytics'))->assertOk()->assertSee('Analítica propia')->assertSee('No almacenamos IP'); }
 public function test_home_and_place_expose_canonical_structured_metadata(): void { $this->seed();$place=Place::where('publication_status','published')->first();$this->get(route('home'))->assertSee('application/ld+json',false)->assertSee('https://schema.org',false)->assertSee('rel="canonical"',false)->assertSee('property="og:image" content="'.asset('brand/compartir-turismosv.png').'"',false)->assertSee('name="twitter:card" content="summary_large_image"',false);$this->get(route('places.show',$place))->assertSee('property="og:image" content="'.asset('brand/compartir-turismosv.png').'"',false)->assertSee('TouristAttraction')->assertSee(route('places.show',$place),false); }
}
