<?php
namespace Tests\Feature;
use App\Models\SocialAccount;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Laravel\Socialite\Contracts\Provider;use Laravel\Socialite\Facades\Socialite;use Laravel\Socialite\Two\User as SocialUser;use Mockery;use Tests\TestCase;
class SocialAuthenticationTest extends TestCase {
 use RefreshDatabase;
 private function remote(string $id,string $email): void { $user=new SocialUser;$user->id=$id;$user->name='Viajero Social';$user->email=$email;$provider=Mockery::mock(Provider::class);$provider->shouldReceive('user')->once()->andReturn($user);Socialite::shouldReceive('driver')->once()->andReturn($provider); }
 public function test_new_social_identity_requires_legal_consent_before_creation(): void { $this->remote('google-1','nuevo@example.com');$this->get(route('social.callback','google'))->assertRedirect(route('social.consent'));$this->assertDatabaseCount('users',0);$this->get(route('social.consent'))->assertOk()->assertSee('nuevo@example.com');$this->post(route('social.complete'))->assertSessionHasErrors('terms');$this->post(route('social.complete'),['terms'=>'1'])->assertRedirect(route('interests.edit'));$this->assertDatabaseHas('users',['email'=>'nuevo@example.com']);$this->assertDatabaseHas('social_accounts',['provider'=>'google','provider_user_id'=>'google-1']);$this->assertNotNull(User::first()->email_verified_at); }
 public function test_existing_email_is_never_linked_automatically(): void { User::factory()->create(['email'=>'existente@example.com']);$this->remote('facebook-1','existente@example.com');$this->get(route('social.callback','facebook'))->assertRedirect(route('login'))->assertSessionHasErrors('social');$this->assertDatabaseCount('social_accounts',0); }
 public function test_connected_identity_logs_in_and_authenticated_user_can_connect_provider(): void { $user=User::factory()->create(['email_verified_at'=>now()]);SocialAccount::create(['user_id'=>$user->id,'provider'=>'google','provider_user_id'=>'known','provider_email'=>$user->email,'connected_at'=>now()]);$this->remote('known',$user->email);$this->get(route('social.callback','google'))->assertRedirect(route('profile'));$this->assertAuthenticatedAs($user);$this->post(route('logout'));$this->actingAs($user);$this->remote('fb-known',$user->email);$this->get(route('social.callback','facebook'))->assertRedirect(route('profile'));$this->assertDatabaseHas('social_accounts',['user_id'=>$user->id,'provider'=>'facebook','provider_user_id'=>'fb-known']); }
 public function test_missing_credentials_fail_safely_without_external_request(): void { config(['services.google.client_id'=>null,'services.google.client_secret'=>null]);$this->get(route('social.redirect','google'))->assertRedirect()->assertSessionHasErrors('social');$this->get('/acceso/instagram')->assertNotFound(); }
}
