<?php
namespace Tests\Feature;
use App\Models\SponsorshipCampaign;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class SponsorshipTest extends TestCase {use RefreshDatabase;
 private function payload():array{return ['sponsor_name'=>'Comercio aliado','title'=>'Descubre una experiencia especial','description'=>'Una propuesta identificada claramente como contenido patrocinado.','destination_url'=>'https://example.com/campana','starts_on'=>today()->toDateString(),'ends_on'=>today()->addWeek()->toDateString(),'status'=>'active'];}
 public function test_only_admin_creates_campaign():void{$this->seed();$user=User::factory()->create(['email_verified_at'=>now()]);$admin=User::factory()->create(['role'=>'admin','email_verified_at'=>now()]);$this->actingAs($user)->post(route('admin.sponsorships.store'),$this->payload())->assertForbidden();$this->actingAs($admin)->post(route('admin.sponsorships.store'),$this->payload())->assertSessionHasNoErrors();$this->assertDatabaseCount('sponsorship_campaigns',1);}
 public function test_active_campaign_is_disclosed_and_does_not_change_rankings():void{$this->seed();$admin=User::factory()->create();$campaign=SponsorshipCampaign::create($this->payload()+['created_by'=>$admin->id]);$rankedIds=\App\Models\Place::where('publication_status','published')->orderBy('id')->pluck('id');$this->get(route('home'))->assertOk()->assertSee('Contenido patrocinado')->assertSee('No modifica rankings')->assertSee('rel="sponsored nofollow"',false);$this->assertEquals($rankedIds,\App\Models\Place::where('publication_status','published')->orderBy('id')->pluck('id'));$this->assertSame(1,$campaign->fresh()->impressions);$this->get(route('sponsorships.click',$campaign))->assertRedirect('https://example.com/campana');$this->assertSame(1,$campaign->fresh()->clicks);}
 public function test_inactive_campaign_is_not_public():void{$this->seed();$admin=User::factory()->create();SponsorshipCampaign::create(array_merge($this->payload(),['created_by'=>$admin->id,'status'=>'paused']));$this->get(route('home'))->assertDontSee('Contenido patrocinado');}
}
