<?php
namespace Tests\Feature;
use App\Models\Place;
use App\Models\PlacePhoto;
use App\Models\User;
use App\Models\WeeklyPostcardEntry;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Tests\TestCase;
class WeeklyPostcardTest extends TestCase {
    use RefreshDatabase;
    private function photo(User $user,Place $place,string $status='approved'): PlacePhoto { Storage::fake('local');$file=UploadedFile::fake()->image(Str::random(8).'.jpg',1200,800);$path=$file->storeAs("community-photos/{$place->id}",Str::uuid().'.jpg','local');return PlacePhoto::create(['public_id'=>(string)Str::uuid(),'place_id'=>$place->id,'user_id'=>$user->id,'storage_path'=>$path,'original_name'=>'postal.jpg','mime_type'=>'image/jpeg','file_size'=>$file->getSize(),'status'=>$status,'license_version'=>'community-photo-2026-08','rights_confirmed_at'=>now()]); }
    public function test_only_owner_can_nominate_approved_photo_from_public_place(): void { $this->seed();$owner=User::factory()->create(['email_verified_at'=>now()]);$other=User::factory()->create(['email_verified_at'=>now()]);$photo=$this->photo($owner,Place::where('publication_status','published')->first());$this->actingAs($other)->post(route('postcards.nominate',$photo))->assertForbidden();$this->actingAs($owner)->post(route('postcards.nominate',$photo))->assertRedirect();$this->assertDatabaseCount('weekly_postcard_entries',1); }
    public function test_verified_user_has_one_weekly_vote_and_cannot_self_vote(): void { $this->seed();$place=Place::where('publication_status','published')->first();$ownerA=User::factory()->create(['email_verified_at'=>now()]);$ownerB=User::factory()->create(['email_verified_at'=>now()]);$voter=User::factory()->create(['email_verified_at'=>now()]);$a=WeeklyPostcardEntry::create(['place_photo_id'=>$this->photo($ownerA,$place)->id,'user_id'=>$ownerA->id,'week_start'=>now()->startOfWeek()]);$b=WeeklyPostcardEntry::create(['place_photo_id'=>$this->photo($ownerB,$place)->id,'user_id'=>$ownerB->id,'week_start'=>now()->startOfWeek()]);$this->actingAs($ownerA)->post(route('postcards.vote',$a))->assertSessionHasErrors('vote');$this->actingAs($voter)->post(route('postcards.vote',$a))->assertSessionHasNoErrors();$this->actingAs($voter)->post(route('postcards.vote',$b))->assertSessionHasErrors('vote');$this->assertDatabaseCount('weekly_postcard_votes',1); }
    public function test_unverified_account_cannot_nominate_or_vote(): void { $this->seed();$owner=User::factory()->create(['email_verified_at'=>now()]);$unverified=User::factory()->unverified()->create();$photo=$this->photo($owner,Place::where('publication_status','published')->first());$entry=WeeklyPostcardEntry::create(['place_photo_id'=>$photo->id,'user_id'=>$owner->id,'week_start'=>now()->startOfWeek()]);$this->actingAs($unverified)->post(route('postcards.vote',$entry))->assertRedirect(route('verification.notice'));$this->actingAs($unverified)->post(route('postcards.nominate',$photo))->assertRedirect(route('verification.notice')); }
    public function test_admin_closes_past_week_using_recorded_vote_count(): void { $this->seed();$place=Place::where('publication_status','published')->first();$admin=User::factory()->create(['role'=>'admin','email_verified_at'=>now()]);$aUser=User::factory()->create();$bUser=User::factory()->create();$week=now()->subWeek()->startOfWeek();$a=WeeklyPostcardEntry::create(['place_photo_id'=>$this->photo($aUser,$place)->id,'user_id'=>$aUser->id,'week_start'=>$week]);$b=WeeklyPostcardEntry::create(['place_photo_id'=>$this->photo($bUser,$place)->id,'user_id'=>$bUser->id,'week_start'=>$week]);foreach(User::factory()->count(2)->create() as $voter)$b->votes()->create(['user_id'=>$voter->id,'week_start'=>$week]);$a->votes()->create(['user_id'=>User::factory()->create()->id,'week_start'=>$week]);$this->actingAs($admin)->post(route('admin.postcards.select'),['week_start'=>$week->toDateString()])->assertSessionHasNoErrors();$this->assertTrue($b->fresh()->is_winner);$this->assertFalse($a->fresh()->is_winner);$this->assertSame($admin->id,$b->fresh()->selected_by); }
}
