<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Pasaporte turístico de {{ $displayName }} en TurismoSV."><title>{{ $displayName }} — Viajero TurismoSV</title><link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">@vite(['resources/css/app.css','resources/js/app.js'])<x-social-meta :title="$displayName.' — Viajero TurismoSV'" :description="'Pasaporte turístico de '.$displayName.' en TurismoSV.'" />
<x-analytics />
</head><body class="traveler-public-page">
<header class="place-header"><a href="{{ route('home') }}"><img src="{{ asset('brand/logo-turismosv.svg') }}" alt="TurismoSV"></a><nav><a href="{{ route('home') }}#lugares">Explorar El Salvador</a><a href="{{ route('register') }}">Crear mi pasaporte</a></nav></header>
<main class="traveler-public-shell"><section class="traveler-hero"><div class="traveler-avatar">{{ mb_strtoupper(mb_substr($displayName,0,1)) }}</div><div><p class="eyebrow light">Pasaporte comunitario</p><h1>{{ $displayName }}</h1><p>Viajero de la comunidad TurismoSV. Sus avances proceden únicamente de visitas verificadas.</p></div><img src="{{ asset('brand/isotipo-turismosv.svg') }}" alt=""></section>
@if($traveler->show_public_stamps || $traveler->show_public_achievements)<section class="traveler-stats">@if($traveler->show_public_stamps)<div><strong>{{ $stats['places'] }}</strong><span>Lugares verificados</span></div><div><strong>{{ $stats['departments'] }}</strong><span>Departamentos</span></div>@endif @if($traveler->show_public_achievements)<div><strong>{{ $stats['achievements'] }}</strong><span>Logros obtenidos</span></div>@endif</section>@endif
@if($traveler->show_public_achievements)<section class="public-collection"><div class="section-heading"><div><p class="eyebrow">Progreso acreditado</p><h2>Logros</h2></div></div>@if($achievements->isNotEmpty())<div class="achievement-grid">@foreach($achievements as $achievement)<article class="achievement-card"><span>{{ $achievement->icon }}</span><div><small>LOGRO OBTENIDO</small><h3>{{ $achievement->name }}</h3><p>{{ $achievement->description }}</p></div></article>@endforeach</div>@else<p class="public-empty">Todavía no hay logros para mostrar.</p>@endif</section>@endif
@if($traveler->show_public_stamps)<section class="public-collection"><div class="section-heading"><div><p class="eyebrow">Visitas verificadas</p><h2>Sellos</h2></div></div>@if($stamps->isNotEmpty())<div class="stamp-grid">@foreach($stamps as $stamp)<article class="passport-stamp"><div class="stamp-seal"><img src="{{ asset('brand/isotipo-turismosv.svg') }}" alt=""><span>✓</span></div><p>{{ $stamp->place->category->name }}</p><h3>{{ $stamp->place->name }}</h3><small>{{ $stamp->place->department->name }} · {{ $stamp->earned_at->translatedFormat('M Y') }}</small><footer><a href="{{ route('places.show',$stamp->place) }}">Conocer lugar →</a></footer></article>@endforeach</div>@else<p class="public-empty">Todavía no hay sellos para mostrar.</p>@endif</section>@endif
<section class="public-profile-notice">TurismoSV no muestra el correo, las visitas pendientes ni la ubicación en tiempo real de este viajero. La visibilidad puede ser retirada por el titular.</section></main></body></html>
