<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{{ $achievement->name }} — TurismoSV</title><link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">@vite(['resources/css/app.css','resources/js/app.js'])<x-analytics />
</head><body class="share-card-page">
<header class="place-header"><a href="{{ route('home') }}"><img src="{{ asset('brand/logo-turismosv.svg') }}" alt="TurismoSV"></a><nav><a href="{{ route('passport.show') }}">← Mi pasaporte</a><a href="{{ route('profile') }}">Mi perfil</a></nav></header>
<main class="share-card-shell">
<section><p class="eyebrow">Celebra tu recorrido</p><h1>Tu logro merece viajar.</h1><p>Descarga una imagen vertical lista para historias y publicaciones, o compártela directamente desde un dispositivo compatible.</p><div class="share-card-actions"><button class="primary-button" type="button" data-achievement-share>Compartir tarjeta</button><button class="secondary-button" type="button" data-achievement-download>Descargar PNG</button></div><p class="share-privacy">Solo incluye tu nombre, el logro y la fecha. No publica ubicaciones, correo ni recorridos. Tú decides dónde compartirla.</p><p class="share-feedback" data-share-feedback aria-live="polite"></p></section>
<article class="social-achievement-card" data-achievement-card data-name="{{ $user->name }}" data-achievement="{{ $achievement->name }}" data-description="{{ $achievement->description }}" data-date="{{ $earnedAt->translatedFormat('d \d\e F \d\e Y') }}" data-points="{{ $achievement->points_reward }}" data-logo="{{ asset('brand/isotipo-turismosv.svg') }}">
<div class="social-card-brand"><img src="{{ asset('brand/logo-turismosv.svg') }}" alt="TurismoSV"><span>PASAPORTE DIGITAL</span></div><div class="social-card-seal"><span>{{ $achievement->icon }}</span><small>LOGRO<br>DESBLOQUEADO</small></div><div class="social-card-copy"><p>RECORRIENDO EL SALVADOR</p><h2>{{ $achievement->name }}</h2><p>{{ $achievement->description }}</p></div><footer><div><small>VIAJERO</small><strong>{{ $user->name }}</strong></div><div><small>FECHA</small><strong>{{ $earnedAt->translatedFormat('d M Y') }}</strong></div><b>+{{ $achievement->points_reward }} PTS</b></footer>
</article>
<canvas data-achievement-canvas width="1080" height="1350" hidden></canvas>
</main></body></html>
