<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Mi pasaporte — TurismoSV</title><link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">@vite(['resources/css/app.css','resources/js/app.js'])</head><body class="passport-page">
<header class="place-header"><a href="{{ route('home') }}"><img src="{{ asset('brand/logo-turismosv.svg') }}" alt="TurismoSV"></a><nav><a href="{{ route('home') }}#lugares">Explorar</a><a href="{{ route('profile') }}">Mi perfil</a></nav></header>
<main class="digital-passport">
@if(session('status'))<div class="status-message">{{ session('status') }}</div>@endif
<section class="passport-cover"><div><p>PASAPORTE TURÍSTICO DIGITAL</p><h1>El Salvador<br>se descubre paso a paso.</h1><span>{{ $user->name }}</span></div><img src="{{ asset('brand/isotipo-turismosv.svg') }}" alt=""><small>SV · {{ str_pad($user->id,6,'0',STR_PAD_LEFT) }}</small></section>
<section class="passport-progress"><div><strong>{{ $stats['places'] }}</strong><span>lugares sellados</span></div><div><strong>{{ $stats['departments'] }}<small>/14</small></strong><span>departamentos</span></div><div><strong>{{ $stats['categories'] }}</strong><span>categorías</span></div><div class="passport-share-teaser"><span>Compartir logros</span><strong>Próximo incremento →</strong></div></section>
<section class="stamp-book"><div class="section-heading"><div><p class="eyebrow">Colección verificable</p><h2>Mis sellos</h2></div><p class="section-note">Solo aparecen visitas cuya evidencia fue aprobada.</p></div>
@if($stamps->isNotEmpty())<div class="stamp-grid">@foreach($stamps as $stamp)<article class="passport-stamp"><div class="stamp-seal"><img src="{{ asset('brand/isotipo-turismosv.svg') }}" alt=""><span>✓</span></div><p>{{ $stamp->place->category->name }}</p><h3>{{ $stamp->place->name }}</h3><small>{{ $stamp->place->department->name }} · {{ $stamp->earned_at->translatedFormat('d M Y') }}</small><footer><span>{{ $stamp->stamp_code }}</span><a href="{{ route('places.show',$stamp->place) }}">Ver lugar →</a></footer></article>@endforeach</div>
@else<div class="empty-passport"><img src="{{ asset('brand/isotipo-turismosv.svg') }}" alt=""><h3>Tu primera aventura está esperando.</h3><p>Escanea un QR autorizado o completa otro método de verificación para obtener tu primer sello.</p><a class="primary-button" href="{{ route('home') }}#lugares">Descubrir lugares</a></div>@endif
</section></main></body></html>
