<?php
namespace App\Http\Controllers;
use App\Models\SocialAccount;use App\Models\User;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Auth;use Illuminate\Support\Str;use Illuminate\View\View;use Laravel\Socialite\Facades\Socialite;use Symfony\Component\HttpFoundation\RedirectResponse as SymfonyRedirect;
class SocialAuthController extends Controller {
    private function provider(string $provider): string { abort_unless(in_array($provider,['google','facebook'],true),404);return $provider; }
    public function redirect(string $provider): SymfonyRedirect|RedirectResponse { $provider=$this->provider($provider);if(blank(config("services.{$provider}.client_id"))||blank(config("services.{$provider}.client_secret")))return back()->withErrors(['social'=>'El acceso con '.ucfirst($provider).' todavía no está configurado.']);return Socialite::driver($provider)->redirect(); }
    public function callback(Request $request,string $provider): RedirectResponse { $provider=$this->provider($provider);try{$remote=Socialite::driver($provider)->user();}catch(\Throwable $e){report($e);return redirect()->route('login')->withErrors(['social'=>'No pudimos completar el acceso externo. Intenta nuevamente.']);}
        $account=SocialAccount::where('provider',$provider)->where('provider_user_id',(string)$remote->getId())->first();
        if($request->user()){if($account&&$account->user_id!==$request->user()->id)return redirect()->route('profile')->withErrors(['social'=>'Esta identidad ya está conectada a otra cuenta.']);SocialAccount::updateOrCreate(['user_id'=>$request->user()->id,'provider'=>$provider],['provider_user_id'=>(string)$remote->getId(),'provider_email'=>$remote->getEmail(),'connected_at'=>now()]);return redirect()->route('profile')->with('status',ucfirst($provider).' quedó conectado a tu cuenta.');}
        if($account){Auth::login($account->user);$request->session()->regenerate();return redirect()->intended(route('profile'));}
        $email=Str::lower(trim((string)$remote->getEmail()));if($email===''||User::where('email',$email)->exists())return redirect()->route('login')->withErrors(['social'=>$email===''?'El proveedor no compartió un correo. Utiliza el registro tradicional.':'Ya existe una cuenta con ese correo. Ingresa con tu contraseña y conecta el proveedor desde tu perfil.']);
        $request->session()->put('social_registration',['provider'=>$provider,'provider_user_id'=>(string)$remote->getId(),'name'=>$remote->getName()?:$remote->getNickname()?:'Viajero TurismoSV','email'=>$email]);return redirect()->route('social.consent');
    }
    public function consent(Request $request): View|RedirectResponse { if(!$request->session()->has('social_registration'))return redirect()->route('register');return view('auth.social-consent',['registration'=>$request->session()->get('social_registration')]); }
    public function complete(Request $request): RedirectResponse { $data=$request->session()->get('social_registration');if(!$data)return redirect()->route('register');$request->validate(['terms'=>['accepted']],['terms.accepted'=>'Debes aceptar los Términos y la Política de Privacidad.']);if(User::where('email',$data['email'])->exists())return redirect()->route('login')->withErrors(['social'=>'Ese correo ya fue registrado.']);$user=User::create(['name'=>Str::limit($data['name'],100,''),'email'=>$data['email'],'email_verified_at'=>now(),'password'=>Str::random(48),'role'=>'traveler','terms_accepted_at'=>now(),'terms_version'=>config('app.terms_version','2026-08-25')]);$user->socialAccounts()->create(['provider'=>$data['provider'],'provider_user_id'=>$data['provider_user_id'],'provider_email'=>$data['email'],'connected_at'=>now()]);$request->session()->forget('social_registration');Auth::login($user);$request->session()->regenerate();return redirect()->route('interests.edit')->with('status','Cuenta creada. Ahora elige tus intereses.'); }
}
